[package]
name = "algorithms"
version = "0.1.0"
authors = ["Hale Deng <alanhaledc@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[workspace]
numbers = ['leetcode']